modLoader="javafml"
loaderVersion="[4,)"
license="AllRightsReserved"
issueTrackerURL="https://github.com/ApexStudios-Dev/Issues/issues"

[[mods]]
    modId="apexcore"
    version="${file.jarVersion}"
    displayName="ApexCore"
    credits="Apex - Programming"
    authors="ApexStudios"
    description="ApexCore is a library mod required by all of ApexStudios' mods, such as Fantasy's Furniture, Fantasy's Dice and Infused Foods."
    logoFile="logo.png"
    displayURL="https://modrinth.com/mod/apexcore"

#[[dependencies.apexcore]]
#    modId="minecraft"
#    type="required"
#    versionRange="[1.21.5,1.21.6)"
#    ordering="NONE"
#    side="BOTH"
#[[dependencies.apexcore]]
#    modId="neoforge"
#    type="required"
#    versionRange="[21.5.0-alpha,21.6)"
#    ordering="NONE"
#    side="BOTH"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"
[[mixins]]
   config="META-INF/apexcore.mixins.json"
