modLoader="javafml"
loaderVersion="[4,)"
license="AllRightsReserved"

[[mods]]
    modId="apexcore"
    version="${file.jarVersion}"
    displayName="ApexCore"
    credits="Apex - Programming"
    authors="ApexStudios"
    description="ApexCore is a library mod required by all of ApexStudios' mods, such as Fantasy's Furniture, Fantasy's Dice and Infused Foods."
    logoFile="logo.png"
    displayURL="https://modrinth.com/mod/apexcore"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"
[[mixins]]
   config="META-INF/apexcore.mixins.json"
