name: Check Local Changes

on:
  workflow_run:
    workflows:
      - 'Build PR'
    types:
      - completed

jobs:
  check-local-changes:
    name: Check Local Changes
    uses: ApexStudios-Dev/.github/.github/workflows/check-local-changes.yml@master
