on:
    workflow_dispatch:
    push:
        branches: [ "**/main" ]
        paths: [ "**/src/**" ]

jobs:
    publish:
        uses: ApexStudios-Dev/.github/.github/workflows/publish-mod.yml@master
        secrets: inherit
        with:
            curseforge_id: "550778"
            modrinth_id: "xl3myxch"
            release_type: "alpha"
            name: "ApexCore"
            logo: "https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/minecraft/new/apexcore.png"
            color: "3948743" # 3C40C7
            github_package_url: "https://maven.pkg.github.com/ApexStudios-Dev/ApexCore"
