name: Publish

on:
    workflow_dispatch:
    push:
        branches: [ "**/main" ]
        paths: [ "**/src/**" ]

jobs:
    publish:
        name: Publish ApexCore
        uses: ApexStudios-Dev/.github/.github/workflows/publish-mod.yml@master
        secrets: inherit
        with:
            display_name: ApexCore
            logo_url: https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/minecraft/new/apexcore.png
            color: 0x3358FA
            release_type: alpha
            artifact_id: apexcore
            curseforge_id: "550778"
            modrinth_id: xl3myxch
