name: Publish PRs to GitHub Packages

on:
    workflow_run:
        workflows: [ 'Test PR' ]
        types: [ completed ]
    issue_comment:
        types: [ edited ]
    pull_request:
        types: [ opened ]
    pull_request_target:
        types: [ opened ]
    workflow_call:
        secrets:
            PR_PUBLISHING_GH_APP_ID:
                required: true
            PR_PUBLISHING_GH_APP_KEY:
                required: true

permissions:
    packages: write

jobs:
    publish-pr:
        uses: neoforged/actions/.github/workflows/publish-prs.yml@main
        with:
            artifact_base_path: dev/apexstudios/apexcore/
            uploader_workflow_name: Build PRs
        secrets:
            PR_PUBLISHING_GH_APP_ID: ${{ secrets.PR_PUBLISHING_GH_APP_ID }}
            PR_PUBLISHING_GH_APP_KEY: ${{ secrets.PR_PUBLISHING_GH_APP_KEY }}