name: Publish

on:
  pull_request_target:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened
  workflow_dispatch:
  push:
    branches: [ '**/main' ]
    paths: [ '**/src/**' ]

jobs:
  publish-mod:
    uses: ApexStudios-Dev/.github/.github/workflows/_publish-mod.yml@master
    secrets: inherit
    with:
      java-version: 21
      java-vendor: temurin
      publish-task: ':publishReleasePublicationToApexStudios-ReleasesRepository'
      curseforge-id: '835372' # '550778'
      modrinth-id: 'EjjiYArZ' # 'xl3myxch'
      artifact-id: apexcore
      display-name: ApexCore
      release-type: release
      logo-url: 'https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/minecraft/apexcore/logo.png'
      color: 0x3358FA
