name: Test PR

on:
    pull_request:
        types:
            - synchronize
            - opened

jobs:
    publish-pr:
        name: Publish PR
        uses: ./.github/workflows/publish-pr.yml
        secrets:
            PR_PUBLISHING_GH_APP_ID: ${{ secrets.PR_PUBLISHING_GH_APP_ID }}
            PR_PUBLISHING_GH_APP_KEY: ${{ secrets.PR_PUBLISHING_GH_APP_KEY }}

    generate-vars:
        name: Generate Vars
        uses: ApexStudios-Dev/.github/.github/workflows/_generate-vars.yml@master
        secrets: inherit

    publish-maven:
        name: Publish Maven
        needs: [ generate-vars ]
        runs-on: apexstudios
        if: success()
        steps:
            -   name: Checkout Repository
                uses: ApexStudios-Dev/.github/actions/checkout@master

            -   name: Setup Java
                uses: ApexStudios-Dev/.github/actions/setup-java@master
                with:
                    java-version: 21
                    java-vendor: temurin

            -   name: Setup Gradle
                uses: ApexStudios-Dev/.github/actions/setup-gradle@master

            -   name: Publish PR
                if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
                uses: neoforged/action-pr-publishing/upload@v1
                env:
                    VERSION: ${{ needs.generate-vars.outputs.version }}

    publish-pr-post:
        name: Publish PR Post
        uses: ./.github/workflows/publish-pr.yml
        needs: [ publish-maven ]
        secrets:
            PR_PUBLISHING_GH_APP_ID: ${{ secrets.PR_PUBLISHING_GH_APP_ID }}
            PR_PUBLISHING_GH_APP_KEY: ${{ secrets.PR_PUBLISHING_GH_APP_KEY }}
